# Generated by Django 4.1 on 2022-08-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0002_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='injured',
            field=models.CharField(default='not injured', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='no name', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='passes_attempted',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='passes_completed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='postion',
            field=models.CharField(default='no position', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='tackles',
            field=models.IntegerField(null=True),
        ),
    ]
